openapi: "3.0.0"
info:
  title: French Population, Establishment and Salary API
  description: An API to retrieve population, establishment and salary data by department
  version: "1.0.0"
servers:
  - url: http://localhost:5000
paths:
  /population_salary/{code_departement}:
    get:
      summary: Retrieve population and salary data by department code
      parameters:
        - name: code_departement
          in: path
          required: true
          description: Department code
          schema:
            type: string
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PopulationSalaryResponse'
        '404':
          description: Department not found
  /population_salary:
    get:
      summary: Retrieve population, establishment and salary data for all departments
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PopulationSalary'
components:
  schemas:
    PopulationSalary:
      type: object
      properties:
        code_departement:
          type: string
        departement_name:
          type: string
        total_population:
          type: number
        average_salary_all:
          type: number
        average_salary_male:
          type: number
        average_salary_female:
          type: number
        gender_paygap:
          type: number
        population_establishment_correlation:
          type: string
        total_establishments:
          type: integer
    PopulationSalaryResponse:
      type: object
      properties:
        population_salary:
          type: array
          items:
            $ref: '#/components/schemas/PopulationSalary'
        establishment:
          type: array
          items:
            $ref: '#/components/schemas/Establishment'
    Establishment:
      type: object
      properties:
        establishment_property1: # Replace with actual properties
          type: string
        establishment_property2:
          type: string
        # Add more properties as needed
