swagger: "2.0"
info:
  version: "1.0.0"
  title: "French Population and Salary API"
  description: "An API to retrieve population, establishment and salary information by department"
basePath: "/"
schemes:
  - "http"
paths:
  /population_salary/{code_departement}:
    get:
      summary: "Get establishment, population and salary information by department code"
      parameters:
        - name: "code_departement"
          in: "path"
          description: "The department code"
          required: true
          type: "string"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "object"
            properties:
              population_salary:
                type: "array"
                items:
                  $ref: "#/definitions/PopulationSalary"
              establishment:
                type: "array"
                items:
                  $ref: "#/definitions/Establishment"
        404:
          description: "No data found for the given department code"
  /population_salary:
    get:
      summary: "Get establishment, population and salary information for all departments"
      parameters:
        - name: "page"
          in: "query"
          description: "Page number"
          required: false
          type: "integer"
        - name: "page_size"
          in: "query"
          description: "Number of items per page"
          required: false
          type: "integer"
      responses:
        200:
          description: "Successful operation"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/PopulationSalary"
definitions:
  PopulationSalary:
    type: "object"
    properties:
      code_departement:
        type: "string"
      departement_name:
        type: "string"
      total_population:
        type: "number"
      average_salary_all:
        type: "number"
      average_salary_male:
        type: "number"
      average_salary_female:
        type: "number"
      gender_paygap:
        type: "number"
      population_establishment_correlation:
        type: "string"
      total_establishments:
        type: "number"
  Establishment:
    type: "object"
    properties:
      establishment_id:
        type: "integer"
      establishment_name:
        type: "string"
      total_employees:
        type: "integer"
